apiVersion: v1
kind: Pod
metadata:
  labels:
    run: loop
  name: loop
spec:
  containers:
    - image: busybox:1.36.1
      name: loop
      resources: {}
      command: ["/bin/sh", "-c"]
      args:
        - for i in 1 2 3 4 5; do echo "$i - A piece of cake !" ; done; sleep infinity;
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
